site_name: yeastdnnexplorer
site_description: "A collection of objects and functions to work with calling cards sequencing tools"
site_author: "ben mueller <email@email.com>, chase mateusiak <chasem@wustl.edu>, michael brent <brent@wustl.edu>"
# TODO: update this when moved to brentlab
site_url: "https://brentlab.github.io/yeastdnnexplorer/"
# TODO: update this when moved to brentlab
repo_url: "https://github.com/brentlab/yeastdnnexplorer"
repo_name: "yeastdnnexplorer"
edit_uri: "edit/master/docs/"
watch: ['yeastdnnexplorer', 'docs']

theme:
  name: material

plugins:
- search
- autorefs
- section-index
- mknotebooks
- mkdocstrings:
    handlers:
          python:
            paths: [yeastdnnexplorer]  # search packages in the src folder
            merge_init_into_class: True
            options:
              docstring_style: 'sphinx'

nav:
- Home:
    - index.md
- Tutorials:
  - Generate in silico data: tutorials/generate_in_silico_data.ipynb
- API:
    - Probability Models:
      - Generate Gene Population: probability_models/generate_gene_population.md
      - probability_models/GenePopulation.md
      - probability_models/generate_binding_effects.md
      - probability_models/generate_pvalues.md
      - probability_models/generate_perturbation_effects.md
      - probability_models/default_perturbation_effect_adjustment_function.md
- Experiments:
- Models:
  - SimpleModel:
    - ml_models/SimpleModel_init.md
    - ml_models/SimpleModel_forward.md
    - ml_models/configure_optimizers.md
    - ml_models/test_step.md
    - ml_models/training_step.md
    - ml_models/val_step.md
- Data Loaders:
  - SyntheticDataLoader:
    - data_loaders/SyntheticDataLoader_init.md
    - data_loaders/SyntheticDataLoader_prepare_data.md
    - data_loaders/SyntheticDataLoader_setup.md
    - data_loaders/test_dataloader.md
    - data_loaders/train_dataloader.md
    - data_loaders/val_dataloader.md

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
